export const API_CONFIG = {
    BASE_URL: localStorage.getItem("baseUrl") || import.meta.env.VITE_API_BASE_URL || "",
    ENDPOINTS: {
        ACCOUNTS: {
            LOGIN: "/api/Accounts/login",
            LOGOUT: "/api/Accounts/logout",
            REGISTER_STUDENT: "/api/Accounts/registerAsStudent",
            REGISTER_SERVICE: "/api/Accounts/registerAsService",
            GET_CURRENT_USER: "/api/Accounts/getCurrentUser",
            UPDATE_CURRENT_USER: "/api/Accounts/updateCurrentUser",
            ASSIGN_ROLE: "/api/Accounts/assignRole",
            REMOVE_ROLE: "/api/Accounts/removeRole",
            FORGET_PASSWORD: "/api/Accounts/forgetPassword",
            RESET_PASSWORD: "/api/Accounts/resetPassword",
            CHANGE_PASSWORD: "/api/Accounts/changePassword",
            SEND_OTP: "/api/Accounts/sendOTP",
            VERIFY_OTP: "/api/Accounts/verifyOTP",
            REFRESH_TOKEN: "/api/Accounts/refreshToken",
        },
        USERS: {
            GET_ALL: "/api/Users/users",
            GET_ALL_ADMINS: "/api/Users/users/admins",
            ASSIGN_ROLE: "/api/Users/assignRole",
            REMOVE_ROLE: "/api/Users/removeRole",
            ACCEPT: (userId: string) => `/api/Users/${userId}/accept`,
            BLOCK: (userId: string) => `/api/Users/${userId}/block`,
            GET_USER_POSTS: (userId: string) => `/api/House/Users/${userId}/Posts`,
        },
        CHAT: {
            CONVERSATIONS: "/api/Chat/conversations",
            MESSAGES: (conversationId: number) => `/api/Chat/messages/${conversationId}`,
            MARK_READ: (conversationId: number) => `/api/Chat/markAsRead/${conversationId}`,
            ONLINE: (userId: string) => `/api/Chat/online/${userId}`,
            DELETE_CONVERSATION: (id: number) => `/api/Chat/conversations/${id}`,
        },
        HOUSE: {
            GET_ALL: "/api/House/Houses",
            GET_BY_ID: (id: number) => `/api/House/${id}`,
            DASHBOARD_HOUSES: "/api/House/dashboard/Houses",
            DASHBOARD_HOUSE_BY_ID: (id: number) => `/api/House/dashboard/${id}`,
            ACCEPT: (id: number) => `/api/House/${id}/status`,
            TOGGLE_FAVORITE: (id: number) => `/api/House/favorite/${id}`,
            GET_FAVORITES: "/api/House/favorites",
            DELETE: (id: number) => `/api/House/${id}`,
            UPDATE: (id: number) => `/api/House/${id}`,
            DELETE_IMAGE: (houseId: number) => `/api/House/houses/${houseId}/images`,
            // House Types
            GET_TYPES: "/api/House/Types",
            GET_TYPE_BY_ID: (id: number) => `/api/House/HouseType/${id}`,
            CREATE_TYPE: "/api/House/HouseType",
            UPDATE_TYPE: (id: number) => `/api/House/HouseType/${id}`,
            DELETE_TYPE: (id: number) => `/api/House/DeleteHouse/${id}`,
            // Ratings
            ADD_RATING: "/api/House/addRating",
            DELETE_RATING: (id: number) => `/api/House/rating/${id}`,
            GET_ADMIN_RATINGS: "/api/House/ratingHouse",
            PUBLISH_RATING: (id: number) => `/api/House/${id}/publish`,
            // Appointments
            ADD_APPOINTMENT: "/api/House/addAppointment",
            UPDATE_APPOINTMENT: (id: number) => `/api/House/updateAppointment/${id}`,
            DELETE_APPOINTMENT: (id: number) => `/api/House/deleteAppointment/${id}`,
            GET_ALL_APPOINTMENTS: "/api/House/allAppointment",
            GET_APPOINTMENT: (id: number) => `/api/House/appointment/${id}`,
        },
        SERVICES: {
            GET_ALL: "/api/Services/dashboard/Services",
            GET_BY_ID: (id: number) => `/api/Services/${id}`,
            DASHBOARD_GET_BY_ID: (id: number) => `/api/Services/dashboard/${id}`,
            CREATE: "/api/Services",
            UPDATE: (id: number) => `/api/Services/${id}`,
            DELETE: (id: number) => `/api/Services/${id}`,
            UPDATE_STATUS: (id: number) => `/api/Services/${id}/status`,
            ADD_RATING: "/api/Services/services/ratings",
            DELETE_RATING: (id: number) => `/api/Services/services/ratings/${id}`,
            GET_RATINGS: "/api/Services/services/ratingsById",
        },
        SERVICE_CATEGORY: {
            GET_ALL: "/ServiceCategory",
            GET_BY_ID: (id: number) => `/ServiceCategory/${id}`,
            CREATE: "/ServiceCategory",
            UPDATE: (id: number) => `/ServiceCategory/${id}`,
            DELETE: (id: number) => `/ServiceCategory/${id}`,
        },
        HELP_REQUEST: {
            GET_ALL: "/api/HelpRequest",
            GET_BY_ID: (id: number) => `/api/HelpRequest/${id}`,
            DASHBOARD_GET_ALL: "/api/HelpRequest/dashboard",
            DASHBOARD_GET_BY_ID: (id: number) => `/api/HelpRequest/dashboard/${id}`,
            CREATE: "/api/HelpRequest",
            UPDATE: (id: number) => `/api/HelpRequest/${id}`,
            DELETE: (id: number) => `/api/HelpRequest/${id}`,
            UPDATE_STATUS: (id: number) => `/helpRequests/${id}/status`,
        },
        REQUEST_TYPE: {
            GET_ALL: "/requestTypes",
            GET_BY_ID: (id: number) => `/requestTypes/${id}`,
            CREATE: "/requestTypes",
            UPDATE: (id: number) => `/requestTypes/${id}`,
            DELETE: (id: number) => `/requestTypes/${id}`,
        },
        PAGES: {
            MAIN_PAGE: "/api/Pages/mainPage",
        }
    },
    SIGNALR_HUB_URL: "/hubs/chat", // Adjust path as needed, typically hub route
};
